chameleon:
  cuda: 1
  dataset: chameleon
  dropout1: 0.8
  epoch: 2000
  feat_dropout: 0.0
  gamma: 0.5
  hidden_dim: 128
  lr: 0.1
  nclass: 5
  power: 10
  seed: 1
  weight_decay: 0.0001
citeseer:
  cuda: 1
  dataset: citeseer
  dropout1: 0.8
  epoch: 2000
  feat_dropout: 0.4
  gamma: 0.005
  hidden_dim: 32
  lr: 0.005
  nclass: 6
  power: 10
  seed: 1
  weight_decay: 0.001
cora:
  cuda: 1
  dataset: cora
  dropout1: 0.8
  epoch: 2000
  feat_dropout: 0.0
  gamma: 0.005
  hidden_dim: 32
  lr: 0.05
  nclass: 7
  power: 10
  seed: 1
  weight_decay: 0.0005
squirrel:
  cuda: 1
  dataset: squirrel
  dropout1: 0.8
  epoch: 2000
  feat_dropout: 0.8
  gamma: 1
  hidden_dim: 128
  lr: 0.01
  nclass: 5
  power: 10
  seed: 1
  weight_decay: 0.001
