chameleon:
  cuda: 1
  dataset: chameleon
  dropout1: 0.8
  epoch: 2000
  feat_dropout: 0.6
  gamma: 10
  hidden_dim: 128
  lr: 0.1
  nclass: 5
  power: 10
  seed: 1
  weight_decay: 5.0e-06
citeseer:
  cuda: 1
  dataset: citeseer
  dropout1: 0.8
  epoch: 2000
  feat_dropout: 0.2
  gamma: 0.005
  hidden_dim: 16
  lr: 0.05
  nclass: 6
  power: 10
  seed: 1
  weight_decay: 0.0005
cora:
  cuda: 1
  dataset: cora
  dropout1: 0.8
  epoch: 2000
  feat_dropout: 0.2
  gamma: 0.01
  hidden_dim: 32
  lr: 0.1
  nclass: 7
  power: 10
  seed: 1
  weight_decay: 0.0005
squirrel:
  cuda: 1
  dataset: squirrel
  dropout1: 0.6
  epoch: 2000
  feat_dropout: 0.2
  gamma: 5
  hidden_dim: 8
  lr: 0.1
  nclass: 5
  power: 10
  seed: 1
  weight_decay: 0.001
